CREATE TABLE IF NOT EXISTS tms_vehicles (
    id TEXT PRIMARY KEY,
    vehicle_number TEXT NOT NULL UNIQUE,
    vehicle_type TEXT NOT NULL,
    license_plate TEXT NOT NULL,
    vin TEXT,
    make TEXT,
    model TEXT,
    year INTEGER,
    capacity_weight REAL NOT NULL,
    capacity_volume REAL NOT NULL,
    capacity_unit TEXT NOT NULL,
    fuel_type TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Available',
    current_location_lat REAL,
    current_location_lng REAL,
    odometer REAL DEFAULT 0,
    last_maintenance TEXT,
    next_maintenance TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tms_drivers (
    id TEXT PRIMARY KEY,
    employee_id TEXT,
    driver_code TEXT NOT NULL UNIQUE,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    email TEXT,
    license_number TEXT NOT NULL,
    license_class TEXT NOT NULL,
    license_expiry TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Available',
    current_vehicle_id TEXT,
    current_location_lat REAL,
    current_location_lng REAL,
    hours_driven_today REAL DEFAULT 0,
    hours_available REAL DEFAULT 11,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tms_carrier_contracts (
    id TEXT PRIMARY KEY,
    carrier_id TEXT NOT NULL,
    contract_number TEXT NOT NULL UNIQUE,
    contract_name TEXT NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    payment_terms TEXT NOT NULL,
    fuel_surcharge_percent REAL DEFAULT 0,
    accessorial_rates TEXT,
    volume_commitment REAL,
    volume_discount_tiers TEXT,
    is_active INTEGER DEFAULT 1,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tms_freight_rates (
    id TEXT PRIMARY KEY,
    contract_id TEXT NOT NULL,
    origin_zone TEXT NOT NULL,
    destination_zone TEXT NOT NULL,
    service_type TEXT NOT NULL,
    rate_type TEXT NOT NULL,
    base_rate INTEGER NOT NULL,
    per_mile_rate INTEGER DEFAULT 0,
    per_kg_rate INTEGER DEFAULT 0,
    per_pallet_rate INTEGER DEFAULT 0,
    min_charge INTEGER DEFAULT 0,
    max_charge INTEGER,
    currency TEXT NOT NULL DEFAULT 'USD',
    effective_date TEXT NOT NULL,
    expiry_date TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tms_loads (
    id TEXT PRIMARY KEY,
    load_number TEXT NOT NULL UNIQUE,
    carrier_id TEXT,
    driver_id TEXT,
    vehicle_id TEXT,
    status TEXT NOT NULL DEFAULT 'Planned',
    origin_name TEXT NOT NULL,
    origin_street TEXT NOT NULL,
    origin_city TEXT NOT NULL,
    origin_state TEXT,
    origin_postal_code TEXT NOT NULL,
    origin_country TEXT NOT NULL,
    origin_lat REAL,
    origin_lng REAL,
    destination_name TEXT NOT NULL,
    destination_street TEXT NOT NULL,
    destination_city TEXT NOT NULL,
    destination_state TEXT,
    destination_postal_code TEXT NOT NULL,
    destination_country TEXT NOT NULL,
    destination_lat REAL,
    destination_lng REAL,
    planned_pickup TEXT NOT NULL,
    actual_pickup TEXT,
    planned_delivery TEXT NOT NULL,
    actual_delivery TEXT,
    total_weight REAL DEFAULT 0,
    total_volume REAL DEFAULT 0,
    total_pallets INTEGER DEFAULT 0,
    total_pieces INTEGER DEFAULT 0,
    freight_charge INTEGER DEFAULT 0,
    fuel_surcharge INTEGER DEFAULT 0,
    accessorial_charges INTEGER DEFAULT 0,
    total_charge INTEGER DEFAULT 0,
    currency TEXT NOT NULL DEFAULT 'USD',
    distance_miles REAL,
    notes TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tms_load_stops (
    id TEXT PRIMARY KEY,
    load_id TEXT NOT NULL,
    stop_number INTEGER NOT NULL,
    stop_type TEXT NOT NULL,
    location_name TEXT NOT NULL,
    street TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT,
    postal_code TEXT NOT NULL,
    country TEXT NOT NULL,
    lat REAL,
    lng REAL,
    planned_arrival TEXT NOT NULL,
    actual_arrival TEXT,
    planned_departure TEXT NOT NULL,
    actual_departure TEXT,
    appointment_number TEXT,
    instructions TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tms_load_items (
    id TEXT PRIMARY KEY,
    load_id TEXT NOT NULL,
    stop_id TEXT NOT NULL,
    shipment_id TEXT,
    product_id TEXT,
    description TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    weight REAL NOT NULL,
    volume REAL NOT NULL,
    pallets INTEGER NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tms_routes (
    id TEXT PRIMARY KEY,
    route_number TEXT NOT NULL UNIQUE,
    route_name TEXT NOT NULL,
    driver_id TEXT,
    vehicle_id TEXT,
    status TEXT NOT NULL DEFAULT 'Planned',
    planned_start TEXT NOT NULL,
    actual_start TEXT,
    planned_end TEXT NOT NULL,
    actual_end TEXT,
    total_distance REAL DEFAULT 0,
    total_duration_minutes INTEGER DEFAULT 0,
    total_stops INTEGER DEFAULT 0,
    completed_stops INTEGER DEFAULT 0,
    total_weight REAL DEFAULT 0,
    optimization_score REAL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tms_route_stops (
    id TEXT PRIMARY KEY,
    route_id TEXT NOT NULL,
    stop_sequence INTEGER NOT NULL,
    stop_type TEXT NOT NULL,
    load_id TEXT,
    location_name TEXT NOT NULL,
    street TEXT NOT NULL,
    city TEXT NOT NULL,
    state TEXT,
    postal_code TEXT NOT NULL,
    country TEXT NOT NULL,
    lat REAL NOT NULL,
    lng REAL NOT NULL,
    planned_arrival TEXT NOT NULL,
    actual_arrival TEXT,
    planned_duration_minutes INTEGER NOT NULL,
    status TEXT NOT NULL DEFAULT 'Planned',
    notes TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tms_freight_invoices (
    id TEXT PRIMARY KEY,
    invoice_number TEXT NOT NULL UNIQUE,
    carrier_id TEXT NOT NULL,
    load_id TEXT,
    invoice_date TEXT NOT NULL,
    due_date TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Pending',
    base_freight INTEGER NOT NULL,
    fuel_surcharge INTEGER DEFAULT 0,
    accessorial_charges INTEGER DEFAULT 0,
    tax INTEGER DEFAULT 0,
    total_amount INTEGER NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    expected_amount INTEGER NOT NULL,
    variance_amount INTEGER DEFAULT 0,
    variance_reason TEXT,
    approved_by TEXT,
    approved_at TEXT,
    paid_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tms_freight_invoice_lines (
    id TEXT PRIMARY KEY,
    invoice_id TEXT NOT NULL,
    line_number INTEGER NOT NULL,
    charge_type TEXT NOT NULL,
    description TEXT NOT NULL,
    quantity REAL NOT NULL,
    unit TEXT NOT NULL,
    rate INTEGER NOT NULL,
    amount INTEGER NOT NULL,
    expected_amount INTEGER NOT NULL,
    variance INTEGER DEFAULT 0,
    currency TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tms_fuel_purchases (
    id TEXT PRIMARY KEY,
    vehicle_id TEXT,
    driver_id TEXT,
    purchase_date TEXT NOT NULL,
    vendor_name TEXT NOT NULL,
    location TEXT NOT NULL,
    fuel_type TEXT NOT NULL,
    quantity REAL NOT NULL,
    unit TEXT NOT NULL,
    price_per_unit INTEGER NOT NULL,
    total_amount INTEGER NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    odometer REAL NOT NULL,
    receipt_number TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS tms_accessorial_charges (
    id TEXT PRIMARY KEY,
    code TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    default_rate INTEGER NOT NULL,
    currency TEXT NOT NULL DEFAULT 'USD',
    is_active INTEGER DEFAULT 1,
    created_at TEXT NOT NULL
);
