-- EAM (Enterprise Asset Management) tables

CREATE TABLE IF NOT EXISTS equipment_assets (
    id TEXT PRIMARY KEY,
    asset_number TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    asset_type TEXT NOT NULL,
    category TEXT,
    manufacturer TEXT,
    model TEXT,
    serial_number TEXT,
    location_id TEXT,
    department_id TEXT,
    parent_asset_id TEXT,
    installation_date TEXT,
    warranty_end_date TEXT,
    criticality TEXT NOT NULL,
    status TEXT NOT NULL,
    acquisition_cost INTEGER DEFAULT 0,
    depreciation_method TEXT,
    useful_life_years INTEGER,
    current_book_value INTEGER DEFAULT 0,
    meter_type TEXT,
    meter_unit TEXT,
    current_meter_reading INTEGER,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS work_orders (
    id TEXT PRIMARY KEY,
    wo_number TEXT NOT NULL UNIQUE,
    description TEXT NOT NULL,
    work_order_type TEXT NOT NULL,
    priority TEXT NOT NULL,
    asset_id TEXT,
    location_id TEXT,
    failure_code_id TEXT,
    problem_description TEXT,
    cause_description TEXT,
    remedy_description TEXT,
    requested_by TEXT,
    requested_date TEXT NOT NULL,
    required_date TEXT,
    scheduled_start TEXT,
    scheduled_end TEXT,
    actual_start TEXT,
    actual_end TEXT,
    assigned_to TEXT,
    assigned_team_id TEXT,
    status TEXT NOT NULL,
    estimated_labor_hours REAL DEFAULT 0,
    actual_labor_hours REAL DEFAULT 0,
    estimated_cost INTEGER DEFAULT 0,
    actual_cost INTEGER DEFAULT 0,
    downtime_hours REAL DEFAULT 0,
    completion_notes TEXT,
    closed_by TEXT,
    closed_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS pm_schedules (
    id TEXT PRIMARY KEY,
    pm_number TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    asset_id TEXT NOT NULL,
    maintenance_strategy TEXT NOT NULL,
    frequency_type TEXT NOT NULL,
    frequency_value INTEGER NOT NULL,
    last_performed_date TEXT,
    next_due_date TEXT NOT NULL,
    meter_based INTEGER DEFAULT 0,
    last_meter_reading INTEGER,
    next_meter_due INTEGER,
    estimated_duration_hours REAL DEFAULT 0,
    estimated_cost INTEGER DEFAULT 0,
    auto_generate_wo INTEGER DEFAULT 1,
    lead_time_days INTEGER DEFAULT 7,
    checklist_id TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS spare_parts (
    id TEXT PRIMARY KEY,
    part_number TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    category TEXT,
    manufacturer TEXT,
    unit_of_measure TEXT NOT NULL,
    unit_cost INTEGER DEFAULT 0,
    min_stock_level INTEGER DEFAULT 0,
    max_stock_level INTEGER DEFAULT 0,
    reorder_point INTEGER DEFAULT 0,
    current_stock INTEGER DEFAULT 0,
    warehouse_id TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);
