-- Lease Accounting (IFRS 16/ASC 842)
CREATE TABLE IF NOT EXISTS leases (
    id TEXT PRIMARY KEY,
    lease_number TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    lease_type TEXT NOT NULL,
    lessor_id TEXT NOT NULL,
    lessee_id TEXT NOT NULL,
    asset_id TEXT,
    commencement_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    lease_term_months INTEGER NOT NULL,
    renewal_option INTEGER NOT NULL,
    renewal_term_months INTEGER,
    termination_option INTEGER NOT NULL,
    termination_notice_days INTEGER,
    purchase_option INTEGER NOT NULL,
    purchase_option_price INTEGER,
    fair_value_at_commencement INTEGER NOT NULL,
    residual_value_guarantee INTEGER,
    currency TEXT NOT NULL,
    discount_rate REAL NOT NULL,
    implicit_rate REAL,
    incremental_borrowing_rate REAL,
    initial_direct_costs INTEGER NOT NULL,
    lease_incentives INTEGER NOT NULL,
    decommissioning_provision INTEGER,
    status TEXT NOT NULL,
    classification_date TEXT,
    classification_by TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS lease_payments (
    id TEXT PRIMARY KEY,
    lease_id TEXT NOT NULL,
    payment_number TEXT NOT NULL UNIQUE,
    payment_date TEXT NOT NULL,
    due_date TEXT NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    period_number INTEGER NOT NULL,
    fixed_payment INTEGER NOT NULL,
    variable_payment INTEGER NOT NULL,
    escalation_amount INTEGER NOT NULL,
    total_payment INTEGER NOT NULL,
    currency TEXT NOT NULL,
    payment_status TEXT NOT NULL,
    paid_date TEXT,
    paid_amount INTEGER,
    notes TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS right_of_use_assets (
    id TEXT PRIMARY KEY,
    lease_id TEXT NOT NULL UNIQUE,
    asset_number TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    initial_cost INTEGER NOT NULL,
    accumulated_depreciation INTEGER NOT NULL,
    impairment_loss INTEGER NOT NULL,
    net_book_value INTEGER NOT NULL,
    depreciation_method TEXT NOT NULL,
    useful_life_months INTEGER NOT NULL,
    residual_value INTEGER NOT NULL,
    depreciation_start_date TEXT NOT NULL,
    depreciation_end_date TEXT NOT NULL,
    currency TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS lease_liabilities (
    id TEXT PRIMARY KEY,
    lease_id TEXT NOT NULL UNIQUE,
    liability_number TEXT NOT NULL UNIQUE,
    initial_liability INTEGER NOT NULL,
    outstanding_balance INTEGER NOT NULL,
    interest_accrued INTEGER NOT NULL,
    principal_paid INTEGER NOT NULL,
    currency TEXT NOT NULL,
    calculation_date TEXT NOT NULL,
    amortization_method TEXT NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS lease_amortization_schedule (
    id TEXT PRIMARY KEY,
    lease_id TEXT NOT NULL,
    period_number INTEGER NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    opening_liability INTEGER NOT NULL,
    payment INTEGER NOT NULL,
    interest_expense INTEGER NOT NULL,
    principal_reduction INTEGER NOT NULL,
    closing_liability INTEGER NOT NULL,
    opening_rou_asset INTEGER NOT NULL,
    depreciation_expense INTEGER NOT NULL,
    closing_rou_asset INTEGER NOT NULL,
    total_expense INTEGER NOT NULL,
    currency TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS lease_modifications (
    id TEXT PRIMARY KEY,
    modification_number TEXT NOT NULL UNIQUE,
    lease_id TEXT NOT NULL,
    modification_date TEXT NOT NULL,
    effective_date TEXT NOT NULL,
    modification_type TEXT NOT NULL,
    reason TEXT NOT NULL,
    original_term_months INTEGER NOT NULL,
    new_term_months INTEGER NOT NULL,
    original_payment INTEGER NOT NULL,
    new_payment INTEGER NOT NULL,
    original_discount_rate REAL NOT NULL,
    new_discount_rate REAL,
    remeasurement_gain_loss INTEGER NOT NULL,
    rou_adjustment INTEGER NOT NULL,
    liability_adjustment INTEGER NOT NULL,
    currency TEXT NOT NULL,
    approved_by TEXT,
    approved_at TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS lease_disclosures (
    id TEXT PRIMARY KEY,
    reporting_period TEXT NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    total_finance_leases INTEGER NOT NULL,
    total_operating_leases INTEGER NOT NULL,
    total_rou_assets INTEGER NOT NULL,
    total_lease_liabilities INTEGER NOT NULL,
    total_depreciation INTEGER NOT NULL,
    total_interest INTEGER NOT NULL,
    total_lease_payments INTEGER NOT NULL,
    maturities_within_1_year INTEGER NOT NULL,
    maturities_1_to_5_years INTEGER NOT NULL,
    maturities_after_5_years INTEGER NOT NULL,
    total_undiscounted_payments INTEGER NOT NULL,
    weighted_avg_lease_term REAL NOT NULL,
    weighted_avg_discount_rate REAL NOT NULL,
    currency TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- Bank Integration
CREATE TABLE IF NOT EXISTS bank_connections (
    id TEXT PRIMARY KEY,
    connection_number TEXT NOT NULL UNIQUE,
    bank_name TEXT NOT NULL,
    bank_code TEXT,
    swift_code TEXT,
    api_endpoint TEXT,
    api_key TEXT,
    api_secret TEXT,
    certificate_path TEXT,
    authentication_type TEXT NOT NULL,
    statement_format TEXT NOT NULL,
    polling_enabled INTEGER NOT NULL,
    polling_interval_minutes INTEGER NOT NULL,
    last_poll_at TEXT,
    last_successful_at TEXT,
    last_error TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_accounts (
    id TEXT PRIMARY KEY,
    connection_id TEXT NOT NULL,
    account_number TEXT NOT NULL,
    masked_account_number TEXT NOT NULL,
    account_name TEXT NOT NULL,
    account_type TEXT NOT NULL,
    currency TEXT NOT NULL,
    gl_account_id TEXT,
    company_id TEXT NOT NULL,
    bank_branch TEXT,
    iban TEXT,
    routing_number TEXT,
    auto_reconcile INTEGER NOT NULL,
    reconciliation_rules TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_statements (
    id TEXT PRIMARY KEY,
    statement_number TEXT NOT NULL UNIQUE,
    bank_account_id TEXT NOT NULL,
    statement_date TEXT NOT NULL,
    currency TEXT NOT NULL,
    opening_balance INTEGER NOT NULL,
    closing_balance INTEGER NOT NULL,
    total_credits INTEGER NOT NULL,
    total_debits INTEGER NOT NULL,
    credit_count INTEGER NOT NULL,
    debit_count INTEGER NOT NULL,
    statement_format TEXT NOT NULL,
    raw_file_path TEXT,
    imported_at TEXT NOT NULL,
    imported_by TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS bank_transactions (
    id TEXT PRIMARY KEY,
    statement_id TEXT NOT NULL,
    bank_account_id TEXT NOT NULL,
    transaction_date TEXT NOT NULL,
    value_date TEXT,
    transaction_type TEXT NOT NULL,
    amount INTEGER NOT NULL,
    currency TEXT NOT NULL,
    reference_number TEXT,
    bank_reference TEXT,
    customer_reference TEXT,
    description TEXT NOT NULL,
    payee_name TEXT,
    payee_account TEXT,
    check_number TEXT,
    additional_info TEXT,
    reconciliation_status TEXT NOT NULL,
    matched_entity_type TEXT,
    matched_entity_id TEXT,
    matched_amount INTEGER,
    match_confidence REAL,
    match_rule TEXT,
    journal_entry_id TEXT,
    notes TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reconciliation_rules (
    id TEXT PRIMARY KEY,
    rule_name TEXT NOT NULL,
    description TEXT,
    bank_account_id TEXT,
    match_criteria TEXT NOT NULL,
    tolerance_type TEXT NOT NULL,
    tolerance_value REAL NOT NULL,
    date_tolerance_days INTEGER NOT NULL,
    reference_patterns TEXT,
    auto_match INTEGER NOT NULL,
    priority INTEGER NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reconciliation_sessions (
    id TEXT PRIMARY KEY,
    session_number TEXT NOT NULL UNIQUE,
    bank_account_id TEXT NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    total_transactions INTEGER NOT NULL,
    matched_count INTEGER NOT NULL,
    unmatched_count INTEGER NOT NULL,
    exception_count INTEGER NOT NULL,
    auto_matched_count INTEGER NOT NULL,
    manual_matched_count INTEGER NOT NULL,
    opening_balance INTEGER NOT NULL,
    closing_balance INTEGER NOT NULL,
    calculated_balance INTEGER NOT NULL,
    variance INTEGER NOT NULL,
    status TEXT NOT NULL,
    started_at TEXT NOT NULL,
    completed_at TEXT,
    completed_by TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS reconciliation_matches (
    id TEXT PRIMARY KEY,
    session_id TEXT NOT NULL,
    bank_transaction_id TEXT NOT NULL,
    entity_type TEXT NOT NULL,
    entity_id TEXT NOT NULL,
    entity_reference TEXT NOT NULL,
    transaction_amount INTEGER NOT NULL,
    entity_amount INTEGER NOT NULL,
    match_difference INTEGER NOT NULL,
    match_type TEXT NOT NULL,
    match_rule TEXT,
    match_confidence REAL NOT NULL,
    matched_at TEXT NOT NULL,
    matched_by TEXT,
    status TEXT NOT NULL,
    notes TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS payment_file_generations (
    id TEXT PRIMARY KEY,
    file_number TEXT NOT NULL UNIQUE,
    bank_account_id TEXT NOT NULL,
    file_type TEXT NOT NULL,
    file_date TEXT NOT NULL,
    value_date TEXT NOT NULL,
    currency TEXT NOT NULL,
    total_amount INTEGER NOT NULL,
    payment_count INTEGER NOT NULL,
    file_content TEXT,
    file_path TEXT,
    status TEXT NOT NULL,
    generated_at TEXT NOT NULL,
    transmitted_at TEXT,
    acknowledged_at TEXT,
    created_at TEXT NOT NULL
);

-- Loyalty Programs
CREATE TABLE IF NOT EXISTS loyalty_programs (
    id TEXT PRIMARY KEY,
    program_number TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    program_type TEXT NOT NULL,
    points_name TEXT NOT NULL,
    earn_rate REAL NOT NULL,
    earn_currency TEXT NOT NULL,
    minimum_points_redemption INTEGER NOT NULL,
    points_expiry_months INTEGER,
    enrollment_bonus INTEGER NOT NULL,
    referral_bonus INTEGER NOT NULL,
    birthday_bonus INTEGER NOT NULL,
    max_points_per_day INTEGER,
    max_points_per_year INTEGER,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS loyalty_tiers (
    id TEXT PRIMARY KEY,
    program_id TEXT NOT NULL,
    tier_type TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    minimum_points INTEGER NOT NULL,
    maximum_points INTEGER,
    earn_multiplier REAL NOT NULL,
    benefits TEXT,
    upgrade_bonus INTEGER NOT NULL,
    color_code TEXT,
    priority INTEGER NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS loyalty_members (
    id TEXT PRIMARY KEY,
    member_number TEXT NOT NULL UNIQUE,
    program_id TEXT NOT NULL,
    customer_id TEXT NOT NULL,
    tier_id TEXT,
    enrollment_date TEXT NOT NULL,
    enrollment_source TEXT,
    total_points_earned INTEGER NOT NULL,
    total_points_redeemed INTEGER NOT NULL,
    available_points INTEGER NOT NULL,
    lifetime_points INTEGER NOT NULL,
    points_expiring INTEGER NOT NULL,
    points_expiring_date TEXT,
    total_rewards_redeemed INTEGER NOT NULL,
    tier_upgrade_date TEXT,
    tier_downgrade_date TEXT,
    referral_code TEXT NOT NULL,
    referred_by TEXT,
    referral_count INTEGER NOT NULL,
    status TEXT NOT NULL,
    last_activity_date TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS loyalty_transactions (
    id TEXT PRIMARY KEY,
    transaction_number TEXT NOT NULL UNIQUE,
    member_id TEXT NOT NULL,
    transaction_type TEXT NOT NULL,
    point_type TEXT NOT NULL,
    points INTEGER NOT NULL,
    running_balance INTEGER NOT NULL,
    source_type TEXT,
    source_id TEXT,
    order_id TEXT,
    amount INTEGER,
    currency TEXT,
    description TEXT,
    expiry_date TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS loyalty_rewards (
    id TEXT PRIMARY KEY,
    reward_number TEXT NOT NULL UNIQUE,
    program_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    reward_type TEXT NOT NULL,
    points_cost INTEGER NOT NULL,
    cash_value INTEGER,
    currency TEXT NOT NULL,
    product_id TEXT,
    discount_percent REAL,
    discount_amount INTEGER,
    min_purchase_amount INTEGER,
    max_redemptions INTEGER,
    redemptions_count INTEGER NOT NULL,
    valid_from TEXT,
    valid_until TEXT,
    tier_requirement TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS loyalty_redemptions (
    id TEXT PRIMARY KEY,
    redemption_number TEXT NOT NULL UNIQUE,
    member_id TEXT NOT NULL,
    reward_id TEXT NOT NULL,
    points_used INTEGER NOT NULL,
    cash_value INTEGER NOT NULL,
    currency TEXT NOT NULL,
    order_id TEXT,
    redemption_date TEXT NOT NULL,
    status TEXT NOT NULL,
    voucher_code TEXT,
    voucher_expires TEXT,
    used_at TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS loyalty_promotions (
    id TEXT PRIMARY KEY,
    promotion_number TEXT NOT NULL UNIQUE,
    program_id TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    promotion_type TEXT NOT NULL,
    earn_multiplier REAL NOT NULL,
    bonus_points INTEGER NOT NULL,
    start_date TEXT NOT NULL,
    end_date TEXT NOT NULL,
    product_ids TEXT,
    category_ids TEXT,
    tier_restriction TEXT,
    max_points_per_member INTEGER,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

-- Partner Relationship Management
CREATE TABLE IF NOT EXISTS partners (
    id TEXT PRIMARY KEY,
    partner_number TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    legal_name TEXT,
    partner_type TEXT NOT NULL,
    tier TEXT NOT NULL,
    parent_partner_id TEXT,
    primary_contact_id TEXT,
    website TEXT,
    email TEXT,
    phone TEXT,
    address TEXT,
    city TEXT,
    state TEXT,
    country TEXT,
    postal_code TEXT,
    tax_id TEXT,
    registration_date TEXT,
    agreement_date TEXT,
    agreement_expiry TEXT,
    contract_value INTEGER,
    currency TEXT NOT NULL,
    commission_rate REAL NOT NULL,
    discount_rate REAL NOT NULL,
    credit_limit INTEGER,
    payment_terms_days INTEGER NOT NULL,
    certification_level TEXT,
    certifications TEXT,
    specializations TEXT,
    regions_served TEXT,
    industries_served TEXT,
    annual_revenue INTEGER,
    employee_count INTEGER,
    notes TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS partner_contacts (
    id TEXT PRIMARY KEY,
    partner_id TEXT NOT NULL,
    first_name TEXT NOT NULL,
    last_name TEXT NOT NULL,
    email TEXT NOT NULL,
    phone TEXT,
    mobile TEXT,
    title TEXT,
    department TEXT,
    is_primary INTEGER NOT NULL,
    receive_notifications INTEGER NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS partner_agreements (
    id TEXT PRIMARY KEY,
    agreement_number TEXT NOT NULL UNIQUE,
    partner_id TEXT NOT NULL,
    agreement_type TEXT NOT NULL,
    name TEXT NOT NULL,
    description TEXT,
    start_date TEXT NOT NULL,
    end_date TEXT,
    auto_renew INTEGER NOT NULL,
    renewal_term_months INTEGER NOT NULL,
    notice_period_days INTEGER NOT NULL,
    commission_rate REAL NOT NULL,
    discount_rate REAL NOT NULL,
    min_sales_target INTEGER,
    max_sales_limit INTEGER,
    territory TEXT,
    exclusivity INTEGER NOT NULL,
    document_path TEXT,
    signed_date TEXT,
    signed_by TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS partner_deals (
    id TEXT PRIMARY KEY,
    deal_number TEXT NOT NULL UNIQUE,
    partner_id TEXT NOT NULL,
    customer_id TEXT,
    customer_name TEXT NOT NULL,
    deal_name TEXT NOT NULL,
    description TEXT,
    deal_type TEXT NOT NULL,
    stage TEXT NOT NULL,
    amount INTEGER NOT NULL,
    currency TEXT NOT NULL,
    expected_close_date TEXT NOT NULL,
    probability INTEGER NOT NULL,
    lead_source TEXT,
    products TEXT,
    partner_commission INTEGER NOT NULL,
    internal_sales_rep_id TEXT,
    partner_contact_id TEXT,
    notes TEXT,
    won_date TEXT,
    lost_date TEXT,
    lost_reason TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS partner_deal_registrations (
    id TEXT PRIMARY KEY,
    registration_number TEXT NOT NULL UNIQUE,
    partner_id TEXT NOT NULL,
    deal_id TEXT,
    customer_name TEXT NOT NULL,
    opportunity_name TEXT NOT NULL,
    estimated_value INTEGER NOT NULL,
    currency TEXT NOT NULL,
    expected_close_date TEXT NOT NULL,
    products TEXT,
    registration_date TEXT NOT NULL,
    expiry_date TEXT NOT NULL,
    status TEXT NOT NULL,
    approved_by TEXT,
    approved_at TEXT,
    rejection_reason TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS partner_commissions (
    id TEXT PRIMARY KEY,
    commission_number TEXT NOT NULL UNIQUE,
    partner_id TEXT NOT NULL,
    deal_id TEXT,
    invoice_id TEXT,
    commission_date TEXT NOT NULL,
    revenue_amount INTEGER NOT NULL,
    commission_rate REAL NOT NULL,
    commission_amount INTEGER NOT NULL,
    currency TEXT NOT NULL,
    status TEXT NOT NULL,
    paid_date TEXT,
    payment_reference TEXT,
    notes TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS partner_performances (
    id TEXT PRIMARY KEY,
    partner_id TEXT NOT NULL,
    period_type TEXT NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    deals_opened INTEGER NOT NULL,
    deals_won INTEGER NOT NULL,
    deals_lost INTEGER NOT NULL,
    total_pipeline INTEGER NOT NULL,
    total_revenue INTEGER NOT NULL,
    total_commission INTEGER NOT NULL,
    win_rate_percent REAL NOT NULL,
    avg_deal_size INTEGER NOT NULL,
    avg_sales_cycle_days REAL NOT NULL,
    customer_satisfaction REAL,
    target_revenue INTEGER,
    attainment_percent REAL,
    currency TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- Procurement/Corporate Cards
CREATE TABLE IF NOT EXISTS corporate_cards (
    id TEXT PRIMARY KEY,
    card_number TEXT NOT NULL UNIQUE,
    masked_number TEXT NOT NULL,
    card_type TEXT NOT NULL,
    cardholder_id TEXT NOT NULL,
    department_id TEXT,
    issuer TEXT NOT NULL,
    card_program TEXT,
    credit_limit INTEGER NOT NULL,
    available_credit INTEGER NOT NULL,
    currency TEXT NOT NULL,
    issue_date TEXT NOT NULL,
    expiry_date TEXT NOT NULL,
    last_four TEXT NOT NULL,
    embossed_name TEXT,
    pin_set INTEGER NOT NULL,
    contactless_enabled INTEGER NOT NULL,
    international_enabled INTEGER NOT NULL,
    atm_enabled INTEGER NOT NULL,
    online_enabled INTEGER NOT NULL,
    mcc_restrictions TEXT,
    merchant_restrictions TEXT,
    daily_limit INTEGER,
    transaction_limit INTEGER,
    status TEXT NOT NULL,
    activated_at TEXT,
    cancelled_at TEXT,
    cancellation_reason TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS card_transactions (
    id TEXT PRIMARY KEY,
    transaction_number TEXT NOT NULL UNIQUE,
    card_id TEXT NOT NULL,
    transaction_date TEXT NOT NULL,
    posting_date TEXT,
    merchant_name TEXT NOT NULL,
    merchant_category TEXT,
    mcc_code TEXT,
    amount INTEGER NOT NULL,
    currency TEXT NOT NULL,
    billing_amount INTEGER NOT NULL,
    billing_currency TEXT NOT NULL,
    transaction_type TEXT NOT NULL,
    status TEXT NOT NULL,
    reference_number TEXT,
    authorization_code TEXT,
    description TEXT,
    receipt_available INTEGER NOT NULL,
    receipt_path TEXT,
    expense_report_id TEXT,
    expense_line_id TEXT,
    reconciled INTEGER NOT NULL,
    reconciled_at TEXT,
    approved_by TEXT,
    approved_at TEXT,
    tax_amount INTEGER,
    tip_amount INTEGER,
    notes TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS card_statements (
    id TEXT PRIMARY KEY,
    statement_number TEXT NOT NULL UNIQUE,
    card_id TEXT NOT NULL,
    statement_date TEXT NOT NULL,
    due_date TEXT NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    opening_balance INTEGER NOT NULL,
    payments INTEGER NOT NULL,
    credits INTEGER NOT NULL,
    purchases INTEGER NOT NULL,
    fees INTEGER NOT NULL,
    interest INTEGER NOT NULL,
    closing_balance INTEGER NOT NULL,
    minimum_payment INTEGER NOT NULL,
    currency TEXT NOT NULL,
    paid_amount INTEGER,
    paid_date TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS card_policies (
    id TEXT PRIMARY KEY,
    policy_number TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    card_type TEXT NOT NULL,
    default_limit INTEGER NOT NULL,
    daily_limit INTEGER,
    transaction_limit INTEGER,
    mcc_allowed TEXT,
    mcc_blocked TEXT,
    merchant_blocked TEXT,
    requires_approval_over INTEGER,
    approval_workflow_id TEXT,
    requires_receipt_over INTEGER,
    auto_reconcile INTEGER NOT NULL,
    international_allowed INTEGER NOT NULL,
    atm_allowed INTEGER NOT NULL,
    online_allowed INTEGER NOT NULL,
    contactless_allowed INTEGER NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS card_disputes (
    id TEXT PRIMARY KEY,
    dispute_number TEXT NOT NULL UNIQUE,
    card_id TEXT NOT NULL,
    transaction_id TEXT NOT NULL,
    dispute_type TEXT NOT NULL,
    dispute_reason TEXT NOT NULL,
    disputed_amount INTEGER NOT NULL,
    currency TEXT NOT NULL,
    filed_date TEXT NOT NULL,
    resolution_date TEXT,
    resolution TEXT,
    provisional_credit INTEGER,
    provisional_credit_date TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS virtual_cards (
    id TEXT PRIMARY KEY,
    parent_card_id TEXT,
    cardholder_id TEXT NOT NULL,
    masked_number TEXT NOT NULL,
    credit_limit INTEGER NOT NULL,
    available_credit INTEGER NOT NULL,
    currency TEXT NOT NULL,
    valid_from TEXT NOT NULL,
    valid_until TEXT NOT NULL,
    single_use INTEGER NOT NULL,
    merchant_lock TEXT,
    usage_limit INTEGER,
    usage_count INTEGER NOT NULL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- Sales Territory Management
CREATE TABLE IF NOT EXISTS sales_territories (
    id TEXT PRIMARY KEY,
    territory_number TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    parent_territory_id TEXT,
    territory_type TEXT NOT NULL,
    manager_id TEXT,
    geography TEXT,
    countries TEXT,
    states TEXT,
    cities TEXT,
    postal_codes TEXT,
    industries TEXT,
    company_size TEXT,
    custom_criteria TEXT,
    effective_date TEXT NOT NULL,
    end_date TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS territory_assignments (
    id TEXT PRIMARY KEY,
    territory_id TEXT NOT NULL,
    sales_rep_id TEXT NOT NULL,
    assignment_type TEXT NOT NULL,
    primary_rep INTEGER NOT NULL,
    effective_date TEXT NOT NULL,
    end_date TEXT,
    allocation_percent INTEGER NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sales_quotas (
    id TEXT PRIMARY KEY,
    quota_number TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    quota_type TEXT NOT NULL,
    owner_type TEXT NOT NULL,
    owner_id TEXT NOT NULL,
    territory_id TEXT,
    fiscal_year INTEGER NOT NULL,
    period_type TEXT NOT NULL,
    currency TEXT NOT NULL,
    annual_target INTEGER NOT NULL,
    q1_target INTEGER NOT NULL,
    q2_target INTEGER NOT NULL,
    q3_target INTEGER NOT NULL,
    q4_target INTEGER NOT NULL,
    m1_target INTEGER NOT NULL,
    m2_target INTEGER NOT NULL,
    m3_target INTEGER NOT NULL,
    m4_target INTEGER NOT NULL,
    m5_target INTEGER NOT NULL,
    m6_target INTEGER NOT NULL,
    m7_target INTEGER NOT NULL,
    m8_target INTEGER NOT NULL,
    m9_target INTEGER NOT NULL,
    m10_target INTEGER NOT NULL,
    m11_target INTEGER NOT NULL,
    m12_target INTEGER NOT NULL,
    product_id TEXT,
    product_category_id TEXT,
    status TEXT NOT NULL,
    approved_by TEXT,
    approved_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS quota_attainments (
    id TEXT PRIMARY KEY,
    quota_id TEXT NOT NULL,
    period_type TEXT NOT NULL,
    period_number INTEGER NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    target INTEGER NOT NULL,
    actual INTEGER NOT NULL,
    attainment_percent REAL NOT NULL,
    pipeline INTEGER NOT NULL,
    pipeline_coverage REAL NOT NULL,
    gap_to_quota INTEGER NOT NULL,
    currency TEXT NOT NULL,
    calculated_at TEXT NOT NULL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS territory_performances (
    id TEXT PRIMARY KEY,
    territory_id TEXT NOT NULL,
    period_type TEXT NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    quota INTEGER NOT NULL,
    revenue INTEGER NOT NULL,
    attainment_percent REAL NOT NULL,
    new_accounts INTEGER NOT NULL,
    total_accounts INTEGER NOT NULL,
    opportunities_created INTEGER NOT NULL,
    opportunities_won INTEGER NOT NULL,
    win_rate_percent REAL NOT NULL,
    avg_deal_size INTEGER NOT NULL,
    pipeline_value INTEGER NOT NULL,
    currency TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- Predictive Maintenance
CREATE TABLE IF NOT EXISTS asset_sensors (
    id TEXT PRIMARY KEY,
    sensor_number TEXT NOT NULL UNIQUE,
    asset_id TEXT NOT NULL,
    name TEXT NOT NULL,
    sensor_type TEXT NOT NULL,
    manufacturer TEXT,
    model TEXT,
    serial_number TEXT,
    location TEXT,
    measurement_unit TEXT NOT NULL,
    sampling_interval_seconds INTEGER NOT NULL,
    data_source TEXT NOT NULL,
    connection_type TEXT NOT NULL,
    last_reading REAL,
    last_reading_at TEXT,
    min_threshold REAL,
    max_threshold REAL,
    alert_threshold_low REAL,
    alert_threshold_high REAL,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS sensor_readings (
    id TEXT PRIMARY KEY,
    sensor_id TEXT NOT NULL,
    reading_timestamp TEXT NOT NULL,
    value REAL NOT NULL,
    unit TEXT NOT NULL,
    quality TEXT NOT NULL,
    raw_value REAL,
    is_anomaly INTEGER NOT NULL,
    anomaly_score REAL,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS predictive_models (
    id TEXT PRIMARY KEY,
    model_number TEXT NOT NULL UNIQUE,
    name TEXT NOT NULL,
    description TEXT,
    model_type TEXT NOT NULL,
    algorithm TEXT NOT NULL,
    version TEXT NOT NULL,
    asset_type_id TEXT,
    target_variable TEXT NOT NULL,
    features TEXT NOT NULL,
    training_data_start TEXT,
    training_data_end TEXT,
    training_samples INTEGER NOT NULL,
    accuracy REAL NOT NULL,
    precision REAL NOT NULL,
    recall REAL NOT NULL,
    f1_score REAL NOT NULL,
    auc_roc REAL,
    confusion_matrix TEXT,
    feature_importance TEXT,
    model_path TEXT,
    hyperparameters TEXT,
    retraining_frequency_days INTEGER NOT NULL,
    last_trained_at TEXT,
    status TEXT NOT NULL,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS asset_health_scores (
    id TEXT PRIMARY KEY,
    asset_id TEXT NOT NULL,
    score_date TEXT NOT NULL,
    overall_score REAL NOT NULL,
    previous_score REAL,
    score_change REAL,
    trend TEXT NOT NULL,
    reliability_score REAL NOT NULL,
    performance_score REAL NOT NULL,
    maintenance_score REAL NOT NULL,
    component_scores TEXT,
    risk_level TEXT NOT NULL,
    days_to_failure INTEGER,
    recommended_action TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS failure_predictions (
    id TEXT PRIMARY KEY,
    prediction_number TEXT NOT NULL UNIQUE,
    asset_id TEXT NOT NULL,
    model_id TEXT,
    prediction_type TEXT NOT NULL,
    prediction_date TEXT NOT NULL,
    predicted_failure_date TEXT NOT NULL,
    confidence REAL NOT NULL,
    failure_mode TEXT,
    failure_probability REAL NOT NULL,
    remaining_useful_life_days INTEGER,
    health_score_at_prediction REAL NOT NULL,
    contributing_factors TEXT,
    recommended_actions TEXT,
    priority INTEGER NOT NULL,
    estimated_repair_cost INTEGER,
    currency TEXT NOT NULL,
    status TEXT NOT NULL,
    actual_failure_date TEXT,
    work_order_id TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS maintenance_schedules (
    id TEXT PRIMARY KEY,
    schedule_number TEXT NOT NULL UNIQUE,
    asset_id TEXT NOT NULL,
    maintenance_type TEXT NOT NULL,
    scheduled_date TEXT NOT NULL,
    estimated_duration_hours REAL NOT NULL,
    estimated_cost INTEGER NOT NULL,
    currency TEXT NOT NULL,
    priority INTEGER NOT NULL,
    prediction_id TEXT,
    description TEXT,
    tasks TEXT,
    parts_required TEXT,
    assigned_to TEXT,
    status TEXT NOT NULL,
    completed_date TEXT,
    actual_cost INTEGER,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS anomaly_detections (
    id TEXT PRIMARY KEY,
    detection_number TEXT NOT NULL UNIQUE,
    asset_id TEXT NOT NULL,
    sensor_id TEXT,
    detection_date TEXT NOT NULL,
    anomaly_type TEXT NOT NULL,
    severity TEXT NOT NULL,
    description TEXT NOT NULL,
    measured_value REAL NOT NULL,
    expected_value REAL,
    deviation_percent REAL,
    detection_method TEXT NOT NULL,
    model_id TEXT,
    acknowledged INTEGER NOT NULL,
    acknowledged_by TEXT,
    acknowledged_at TEXT,
    resolution TEXT,
    resolved_at TEXT,
    created_at TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS maintenance_cost_analyses (
    id TEXT PRIMARY KEY,
    asset_id TEXT NOT NULL,
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    total_maintenance_cost INTEGER NOT NULL,
    preventive_cost INTEGER NOT NULL,
    predictive_cost INTEGER NOT NULL,
    corrective_cost INTEGER NOT NULL,
    downtime_cost INTEGER NOT NULL,
    total_downtime_hours REAL NOT NULL,
    unplanned_downtime_hours REAL NOT NULL,
    mtbf_hours REAL,
    mttr_hours REAL,
    availability_percent REAL NOT NULL,
    oee_percent REAL,
    savings_from_predictions INTEGER NOT NULL,
    currency TEXT NOT NULL,
    created_at TEXT NOT NULL
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_leases_status ON leases(status);
CREATE INDEX IF NOT EXISTS idx_lease_payments_lease ON lease_payments(lease_id);
CREATE INDEX IF NOT EXISTS idx_bank_accounts_connection ON bank_accounts(connection_id);
CREATE INDEX IF NOT EXISTS idx_bank_transactions_account ON bank_transactions(bank_account_id);
CREATE INDEX IF NOT EXISTS idx_loyalty_members_customer ON loyalty_members(customer_id);
CREATE INDEX IF NOT EXISTS idx_loyalty_transactions_member ON loyalty_transactions(member_id);
CREATE INDEX IF NOT EXISTS idx_partners_status ON partners(status);
CREATE INDEX IF NOT EXISTS idx_partner_deals_partner ON partner_deals(partner_id);
CREATE INDEX IF NOT EXISTS idx_corporate_cards_cardholder ON corporate_cards(cardholder_id);
CREATE INDEX IF NOT EXISTS idx_card_transactions_card ON card_transactions(card_id);
CREATE INDEX IF NOT EXISTS idx_sales_territories_manager ON sales_territories(manager_id);
CREATE INDEX IF NOT EXISTS idx_sales_quotas_owner ON sales_quotas(owner_id);
CREATE INDEX IF NOT EXISTS idx_asset_sensors_asset ON asset_sensors(asset_id);
CREATE INDEX IF NOT EXISTS idx_sensor_readings_sensor ON sensor_readings(sensor_id);
CREATE INDEX IF NOT EXISTS idx_failure_predictions_asset ON failure_predictions(asset_id);
CREATE INDEX IF NOT EXISTS idx_anomaly_detections_asset ON anomaly_detections(asset_id);
