use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use uuid::Uuid;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CustomRole {
    pub id: Uuid,
    pub name: String,
    pub code: String,
    pub description: Option<String>,
    pub parent_role_id: Option<Uuid>,
    pub is_system: bool,
    pub is_active: bool,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub created_by: Option<Uuid>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Permission {
    pub id: Uuid,
    pub code: String,
    pub name: String,
    pub description: Option<String>,
    pub module: String,
    pub resource: String,
    pub action: String,
    pub created_at: DateTime<Utc>,
}

impl Permission {
    pub fn full_code(&self) -> String {
        format!("{}:{}:{}", self.module, self.resource, self.action)
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RolePermission {
    pub id: Uuid,
    pub role_id: Uuid,
    pub permission_id: Uuid,
    pub granted_at: DateTime<Utc>,
    pub granted_by: Option<Uuid>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserRoleAssignment {
    pub id: Uuid,
    pub user_id: Uuid,
    pub role_id: Uuid,
    pub assigned_at: DateTime<Utc>,
    pub assigned_by: Option<Uuid>,
    pub expires_at: Option<DateTime<Utc>>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct DataPermission {
    pub id: Uuid,
    pub role_id: Uuid,
    pub resource: String,
    pub filter_type: DataFilterType,
    pub filter_value: String,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize, sqlx::Type)]
#[sqlx(type_name = "TEXT")]
pub enum DataFilterType {
    All,
    Own,
    Department,
    Team,
    Custom,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FieldPermission {
    pub id: Uuid,
    pub role_id: Uuid,
    pub resource: String,
    pub field_name: String,
    pub can_read: bool,
    pub can_write: bool,
    pub can_create: bool,
    pub created_at: DateTime<Utc>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PermissionAuditLog {
    pub id: Uuid,
    pub action: String,
    pub actor_id: Uuid,
    pub target_type: String,
    pub target_id: Uuid,
    pub old_value: Option<String>,
    pub new_value: Option<String>,
    pub performed_at: DateTime<Utc>,
    pub ip_address: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RoleWithPermissions {
    pub role: CustomRole,
    pub permissions: Vec<Permission>,
    pub inherited_from: Option<Uuid>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserPermissionsResult {
    pub user_id: Uuid,
    pub roles: Vec<CustomRole>,
    pub direct_permissions: Vec<Permission>,
    pub effective_permissions: Vec<Permission>,
    pub data_permissions: Vec<DataPermission>,
    pub field_permissions: Vec<FieldPermission>,
}

pub fn get_default_permissions() -> Vec<Permission> {
    vec![
        Permission {
            id: Uuid::nil(),
            code: "finance:accounts:read".into(),
            name: "View Accounts".into(),
            description: Some("View chart of accounts".into()),
            module: "finance".into(),
            resource: "accounts".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "finance:accounts:write".into(),
            name: "Edit Accounts".into(),
            description: Some("Create and edit accounts".into()),
            module: "finance".into(),
            resource: "accounts".into(),
            action: "write".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "finance:accounts:delete".into(),
            name: "Delete Accounts".into(),
            description: Some("Delete accounts".into()),
            module: "finance".into(),
            resource: "accounts".into(),
            action: "delete".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "finance:journals:read".into(),
            name: "View Journals".into(),
            description: Some("View journal entries".into()),
            module: "finance".into(),
            resource: "journals".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "finance:journals:write".into(),
            name: "Create Journals".into(),
            description: Some("Create journal entries".into()),
            module: "finance".into(),
            resource: "journals".into(),
            action: "write".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "finance:journals:post".into(),
            name: "Post Journals".into(),
            description: Some("Post journal entries".into()),
            module: "finance".into(),
            resource: "journals".into(),
            action: "post".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "inventory:products:read".into(),
            name: "View Products".into(),
            description: Some("View product catalog".into()),
            module: "inventory".into(),
            resource: "products".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "inventory:products:write".into(),
            name: "Edit Products".into(),
            description: Some("Create and edit products".into()),
            module: "inventory".into(),
            resource: "products".into(),
            action: "write".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "inventory:products:delete".into(),
            name: "Delete Products".into(),
            description: Some("Delete products".into()),
            module: "inventory".into(),
            resource: "products".into(),
            action: "delete".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "inventory:stock:read".into(),
            name: "View Stock".into(),
            description: Some("View stock levels".into()),
            module: "inventory".into(),
            resource: "stock".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "inventory:stock:adjust".into(),
            name: "Adjust Stock".into(),
            description: Some("Adjust stock levels".into()),
            module: "inventory".into(),
            resource: "stock".into(),
            action: "adjust".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "sales:customers:read".into(),
            name: "View Customers".into(),
            description: Some("View customer list".into()),
            module: "sales".into(),
            resource: "customers".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "sales:customers:write".into(),
            name: "Edit Customers".into(),
            description: Some("Create and edit customers".into()),
            module: "sales".into(),
            resource: "customers".into(),
            action: "write".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "sales:orders:read".into(),
            name: "View Orders".into(),
            description: Some("View sales orders".into()),
            module: "sales".into(),
            resource: "orders".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "sales:orders:write".into(),
            name: "Create Orders".into(),
            description: Some("Create sales orders".into()),
            module: "sales".into(),
            resource: "orders".into(),
            action: "write".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "sales:orders:approve".into(),
            name: "Approve Orders".into(),
            description: Some("Approve sales orders".into()),
            module: "sales".into(),
            resource: "orders".into(),
            action: "approve".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "purchasing:vendors:read".into(),
            name: "View Vendors".into(),
            description: Some("View vendor list".into()),
            module: "purchasing".into(),
            resource: "vendors".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "purchasing:vendors:write".into(),
            name: "Edit Vendors".into(),
            description: Some("Create and edit vendors".into()),
            module: "purchasing".into(),
            resource: "vendors".into(),
            action: "write".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "purchasing:orders:read".into(),
            name: "View POs".into(),
            description: Some("View purchase orders".into()),
            module: "purchasing".into(),
            resource: "orders".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "purchasing:orders:write".into(),
            name: "Create POs".into(),
            description: Some("Create purchase orders".into()),
            module: "purchasing".into(),
            resource: "orders".into(),
            action: "write".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "purchasing:orders:approve".into(),
            name: "Approve POs".into(),
            description: Some("Approve purchase orders".into()),
            module: "purchasing".into(),
            resource: "orders".into(),
            action: "approve".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "hr:employees:read".into(),
            name: "View Employees".into(),
            description: Some("View employee list".into()),
            module: "hr".into(),
            resource: "employees".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "hr:employees:write".into(),
            name: "Edit Employees".into(),
            description: Some("Create and edit employees".into()),
            module: "hr".into(),
            resource: "employees".into(),
            action: "write".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "hr:payroll:read".into(),
            name: "View Payroll".into(),
            description: Some("View payroll data".into()),
            module: "hr".into(),
            resource: "payroll".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "hr:payroll:write".into(),
            name: "Manage Payroll".into(),
            description: Some("Create and manage payroll".into()),
            module: "hr".into(),
            resource: "payroll".into(),
            action: "write".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "manufacturing:boms:read".into(),
            name: "View BOMs".into(),
            description: Some("View bill of materials".into()),
            module: "manufacturing".into(),
            resource: "boms".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "manufacturing:boms:write".into(),
            name: "Edit BOMs".into(),
            description: Some("Create and edit BOMs".into()),
            module: "manufacturing".into(),
            resource: "boms".into(),
            action: "write".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "manufacturing:workorders:read".into(),
            name: "View Work Orders".into(),
            description: Some("View work orders".into()),
            module: "manufacturing".into(),
            resource: "workorders".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "manufacturing:workorders:write".into(),
            name: "Manage Work Orders".into(),
            description: Some("Create and manage work orders".into()),
            module: "manufacturing".into(),
            resource: "workorders".into(),
            action: "write".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "admin:users:read".into(),
            name: "View Users".into(),
            description: Some("View user list".into()),
            module: "admin".into(),
            resource: "users".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "admin:users:write".into(),
            name: "Manage Users".into(),
            description: Some("Create and manage users".into()),
            module: "admin".into(),
            resource: "users".into(),
            action: "write".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "admin:roles:read".into(),
            name: "View Roles".into(),
            description: Some("View role list".into()),
            module: "admin".into(),
            resource: "roles".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "admin:roles:write".into(),
            name: "Manage Roles".into(),
            description: Some("Create and manage roles".into()),
            module: "admin".into(),
            resource: "roles".into(),
            action: "write".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "admin:settings:read".into(),
            name: "View Settings".into(),
            description: Some("View system settings".into()),
            module: "admin".into(),
            resource: "settings".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "admin:settings:write".into(),
            name: "Edit Settings".into(),
            description: Some("Edit system settings".into()),
            module: "admin".into(),
            resource: "settings".into(),
            action: "write".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "reports:all:read".into(),
            name: "View Reports".into(),
            description: Some("View all reports".into()),
            module: "reports".into(),
            resource: "all".into(),
            action: "read".into(),
            created_at: Utc::now(),
        },
        Permission {
            id: Uuid::nil(),
            code: "reports:all:export".into(),
            name: "Export Reports".into(),
            description: Some("Export reports".into()),
            module: "reports".into(),
            resource: "all".into(),
            action: "export".into(),
            created_at: Utc::now(),
        },
    ]
}
